FROM python:3.12-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python3", "client.py", "input.txt", "1"]  # Change 1 to the appropriate client ID when running multiple clients

